/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class jni_test_JniTestEntry */

#ifndef _Included_jni_test_JniTestEntry
#define _Included_jni_test_JniTestEntry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_test_JniTestEntry
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndkapplication_MainActivity_getStringFromC
        (JNIEnv *, jclass);

/**
 * 拆分文件
 * @return
 */
JNIEXPORT void JNICALL Java_com_example_ndkapplication_MainActivity_diff
        (JNIEnv *, jclass, jstring path_jstr, jstring path_pattern_jstr, jint file_num);

/**
 * 拆分文件
 * @return
 */
JNIEXPORT void JNICALL Java_com_example_ndkapplication_MainActivity_path
        (JNIEnv *, jclass, jstring path_jstr, jint count);


JNIEXPORT void JNICALL Java_com_example_ndkapplication_VideoUtils_decode
        (JNIEnv *, jclass,jstring input_jstr, jstring output_jstr);


JNIEXPORT void JNICALL Java_com_example_ndkapplication_VideoUtils_render
        (JNIEnv *, jclass,jstring input_jstr, jobject surface);


JNIEXPORT void JNICALL Java_com_example_ndkapplication_VideoUtils_paly_sound
        (JNIEnv *, jclass,jstring input_jstr, jstring output_jstr);


#ifdef __cplusplus
}
#endif
#endif
